spring:
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  mail:
    port:
    host:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret:
    access: pmAwd5izmqEULionmIAPrA==
    refresh: lKwppuqF4a+agwP0TIUo
logging:
  level:
    org.springframework.security: trace
