CREATE TABLE IF NOT EXISTS t_user();
CREATE TABLE IF NOT EXISTS t_account();
CREATE TABLE IF NOT EXISTS t_card();
CREATE TABLE IF NOT EXISTS t_role();
CREATE TABLE IF NOT EXISTS t_hisotry();
CREATE TABLE IF NOT EXISTS t_credit_hisotry();